/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './sections/**/*.html',
    './js/**/*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                    '#c0c1ff',
        'on-primary':                 '#1000a9',
        'primary-container':          '#8083ff',
        'on-primary-container':       '#0d0096',
        'primary-fixed':              '#e1e0ff',
        'primary-fixed-dim':          '#c0c1ff',
        'on-primary-fixed':           '#07006c',
        'on-primary-fixed-variant':   '#2f2ebe',
        'secondary':                  '#44e2cd',
        'on-secondary':               '#003731',
        'secondary-container':        '#03c6b2',
        'on-secondary-container':     '#004d44',
        'secondary-fixed':            '#62fae3',
        'secondary-fixed-dim':        '#3cddc7',
        'on-secondary-fixed':         '#00201c',
        'on-secondary-fixed-variant': '#005047',
        'tertiary':                   '#4edea3',
        'on-tertiary':                '#003824',
        'tertiary-container':         '#00885d',
        'on-tertiary-container':      '#000703',
        'tertiary-fixed':             '#6ffbbe',
        'tertiary-fixed-dim':         '#4edea3',
        'on-tertiary-fixed':          '#002113',
        'on-tertiary-fixed-variant':  '#005236',
        'surface':                    '#131313',
        'surface-dim':                '#131313',
        'surface-bright':             '#3a3939',
        'surface-container-lowest':   '#0e0e0e',
        'surface-container-low':      '#1c1b1b',
        'surface-container':          '#201f1f',
        'surface-container-high':     '#2a2a2a',
        'surface-container-highest':  '#353534',
        'surface-variant':            '#353534',
        'surface-tint':               '#c0c1ff',
        'on-surface':                 '#e5e2e1',
        'on-surface-variant':         '#c7c4d7',
        'outline':                    '#908fa0',
        'outline-variant':            '#464554',
        'background':                 '#131313',
        'on-background':              '#e5e2e1',
        'inverse-surface':            '#e5e2e1',
        'inverse-on-surface':         '#313030',
        'inverse-primary':            '#494bd6',
        'error':                      '#ffb4ab',
        'on-error':                   '#690005',
        'error-container':            '#93000a',
        'on-error-container':         '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        'section-padding': '120px',
        'gutter':          '24px',
        'margin-mobile':   '20px',
        'margin-desktop':  '64px',
        'container-max':   '1280px',
        'bento-gap':       '16px',
      },
      fontFamily: {
        'headline-lg':        ['JetBrains Mono', 'monospace'],
        'headline-lg-mobile': ['JetBrains Mono', 'monospace'],
        'headline-md':        ['JetBrains Mono', 'monospace'],
        'code-snippet':       ['JetBrains Mono', 'monospace'],
        'label-sm':           ['JetBrains Mono', 'monospace'],
        'body-lg':            ['Inter', 'sans-serif'],
        'body-md':            ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg':        ['48px', { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2',  fontWeight: '700' }],
        'headline-md':        ['24px', { lineHeight: '1.3',  fontWeight: '600' }],
        'code-snippet':       ['14px', { lineHeight: '1.4',  fontWeight: '400' }],
        'label-sm':           ['12px', { lineHeight: '1.0',  letterSpacing: '0.1em', fontWeight: '500' }],
        'body-lg':            ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '1.5',  fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
